### ISSUE TITLE
Text collapsed with each other on Android when folded

### ISSUE THREAD

**Issue by evianzhow** [jys125773/react-native-tree-select#2]
![wechatimg1](https://user-images.githubusercontent.com/4608342/50135638-d7971780-02cf-11e9-8379-450b2ac57e05.png)
Unfolded was normal, but when some levels were folded, text will collapse with each other.

**Comment by yemengdie** [comment]
请问你解决了没有

**Comment by evianzhow** [comment]
@yemengdie Upgrading react-native to 0.59.10 resolved this issue. Might be something wrong with prior Android implementation.
